apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 1m }
      - setWeight: 40
      - pause: { duration: 1m }
      - setWeight: 60
      - pause: { duration: 1m }
      - setWeight: 80
      - pause: { duration: 1m }
      - setWeight: 100
